version: "3.8"
services:

  # Applications

  catalog-service:
    depends_on:
      - cloudnative-postgres
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_POST=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cloudnative-postgres:5432/cloudnativedb_catalog
      - SPRING_PROFILES_ACTIVE=testdata

  # Backing Services

  cloudnative-postgres:
    image: "postgres:14.4"
    container_name: "cloudnative-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cloudnativedb_catalog
